import { useCallback, useEffect, useState } from "react";
import { View, Text, TextInput, Pressable, ScrollView, Alert } from "react-native";
import { Picker } from "@react-native-picker/picker";
import useCurrentUser from "../src/hooks/useCurrentUser";
import { listMessages, sendMessage, type AppMessage, type MessageRecipient } from "../src/services/messages";
import { listTenants, type Tenant } from "../src/services/tenants";

export default function Messages() {
  const { userDoc } = useCurrentUser(); const isSuperAdmin = userDoc?.role === "super_admin" || (userDoc?.role as string | undefined) === "superadmin";
  const [rows, setRows] = useState<AppMessage[]>([]); const [tenants, setTenants] = useState<Tenant[]>([]); const [recipient, setRecipient] = useState<MessageRecipient>(isSuperAdmin ? "all_tenants" : "super_admin"); const [tenantId, setTenantId] = useState(""); const [subject, setSubject] = useState(""); const [body, setBody] = useState("");
  const load = useCallback(async () => { setRows(await listMessages()); if (isSuperAdmin) setTenants(await listTenants()); }, [isSuperAdmin]); useEffect(() => { void load().catch((e) => Alert.alert("Messages", e.message)); }, [load]);
  async function submit() { try { const sent = await sendMessage({ subject, body, recipient, recipientTenantId: recipient === "tenant_admin" ? tenantId : null, senderName: userDoc?.displayName ?? undefined }); setSubject(""); setBody(""); setRows((current) => [sent, ...current]); Alert.alert("Message sent", "Your message was sent successfully."); } catch (e: any) { Alert.alert("Send failed", e.message ?? String(e)); } }
  return <ScrollView className="flex-1 bg-slate-100 p-4"><Text className="text-2xl font-extrabold text-slate-900">Admin communication</Text><Text className="mt-1 text-base text-slate-700">Send and receive operational messages securely.</Text><View className="mt-4 rounded-2xl bg-white p-4"><Text className="text-lg font-extrabold text-slate-900">Compose message</Text><View className="mt-3 rounded-xl border border-slate-200"><Picker selectedValue={recipient} onValueChange={setRecipient}><Picker.Item label="Super Admin" value="super_admin" />{isSuperAdmin ? <><Picker.Item label="All tenant administrators" value="all_tenants" /><Picker.Item label="Individual tenant administrator" value="tenant_admin" /></> : <Picker.Item label="My organisation staff" value="tenant_staff" />}</Picker></View>{isSuperAdmin && recipient === "tenant_admin" ? <View className="mt-2 rounded-xl border border-slate-200"><Picker selectedValue={tenantId} onValueChange={setTenantId}><Picker.Item label="Select tenant" value="" />{tenants.map((t) => <Picker.Item key={t.id} label={t.name} value={t.id} />)}</Picker></View> : null}<TextInput value={subject} onChangeText={setSubject} placeholder="Subject" className="mt-2 rounded-xl border border-slate-200 p-3" /><TextInput value={body} onChangeText={setBody} placeholder="Write your message..." multiline className="mt-2 min-h-28 rounded-xl border border-slate-200 p-3" /><Pressable onPress={submit} className="mt-3 rounded-xl bg-blue-700 p-3"><Text className="text-center font-bold text-white">Send message</Text></Pressable></View><View className="mt-4 rounded-2xl bg-white p-4"><Text className="text-lg font-extrabold text-slate-900">Inbox</Text>{rows.map((m) => <View key={m.id} className="mt-3 rounded-xl bg-slate-50 p-3"><Text className="font-bold text-slate-900">{m.subject}</Text><Text className="mt-1 text-base text-slate-700">{m.body}</Text></View>)}</View></ScrollView>;
}
