import { useEffect, useMemo, useState } from "react";
import { View, Text, ScrollView, Pressable, ActivityIndicator } from "react-native";
import { useRouter } from "expo-router";
import Svg, { Circle, Path } from "react-native-svg";
import { getStaffGlobalSummary, getAllStaffAttendanceInRange, type StaffAttendanceSummary } from "../../src/services/staffAttendanceSummary";
import { todayISO } from "../../src/services/attendance";
import { useRequireAdmin } from "../../src/hooks/useRouteAuthorization";

function isWeekend(date: string) { const day = new Date(`${date}T12:00:00`).getDay(); return day === 0 || day === 6; }
function startOfMonth() { const d = new Date(); d.setDate(1); return d.toISOString().slice(0, 10); }

export default function StaffWeekendReport() {
  const router = useRouter(); const { loading: authLoading, ready } = useRequireAdmin(); const [from, setFrom] = useState(startOfMonth()); const [to, setTo] = useState(todayISO()); const [rows, setRows] = useState<StaffAttendanceSummary[]>([]); const [records, setRecords] = useState<any[]>([]); const [loading, setLoading] = useState(true);
  async function load() { setLoading(true); try { const [summary, staffRows] = await Promise.all([getStaffGlobalSummary(from, to, true), getAllStaffAttendanceInRange(from, to)]); setRows(summary); setRecords(staffRows.filter((r) => isWeekend(r.date))); } finally { setLoading(false); } }
  useEffect(() => { if (ready) void load(); }, [ready]);
  const totals = useMemo(() => rows.reduce((a, r) => ({ present: a.present + r.presentCount, late: a.late + r.lateCount, absent: a.absent + r.absentCount }), { present: 0, late: 0, absent: 0 }), [rows]);
  const attended = totals.present + totals.late; const total = Math.max(1, attended + totals.absent); const daily = useMemo(() => { const m = new Map<string, number>(); records.forEach((r) => m.set(r.date, (m.get(r.date) ?? 0) + (r.checkInTime ? 1 : 0))); return [...m.entries()].sort(([a], [b]) => a.localeCompare(b)); }, [records]); const max = Math.max(1, ...daily.map(([, n]) => n));
  if (authLoading || !ready || loading) return <View className="flex-1 items-center justify-center"><ActivityIndicator size="large" /></View>;
  return <ScrollView className="flex-1 bg-slate-100"><View className="flex-row items-center border-b border-slate-200 bg-slate-900 p-4"><Pressable onPress={() => router.back()}><Text className="mr-3 text-lg text-white">‹</Text></Pressable><Text className="text-xl font-extrabold text-white">Weekend Staff Reports</Text></View><View className="p-3"><View className="mb-3 flex-row gap-2"><Pressable onPress={load} className="rounded-xl bg-blue-700 px-4 py-3"><Text className="font-bold text-white">Refresh</Text></Pressable><Text className="self-center text-sm text-slate-600">{from} — {to}</Text></View><View className="flex-row flex-wrap gap-2"><Stat label="Present" value={totals.present} color="text-emerald-700" /><Stat label="Late" value={totals.late} color="text-amber-700" /><Stat label="Attended" value={attended} color="text-sky-700" /><Stat label="Absent" value={totals.absent} color="text-red-600" /></View><View className="mt-3 rounded-2xl bg-white p-4"><Text className="text-base font-extrabold text-slate-900">Attendance distribution</Text><View className="mt-3 flex-row items-center"><View className="h-32 w-32 items-center justify-center rounded-full" style={{ backgroundColor: "#e2e8f0" }}><View className="h-20 w-20 items-center justify-center rounded-full bg-white"><Text className="font-extrabold text-slate-800">{Math.round(attended / total * 100)}%</Text></View></View><View className="ml-5 gap-2"><Text className="text-sm font-semibold text-emerald-700">● Present {totals.present}</Text><Text className="text-sm font-semibold text-amber-700">● Late {totals.late}</Text><Text className="text-sm font-semibold text-red-600">● Absent {totals.absent}</Text></View></View></View><View className="mt-3 rounded-2xl bg-white p-4"><Text className="text-base font-extrabold text-slate-900">Attendance by weekend day</Text><View className="mt-4 flex-row items-end gap-2">{daily.map(([date, n]) => <View key={date} className="flex-1 items-center"><Text className="text-xs font-bold text-slate-700">{n}</Text><View className="mt-1 w-full rounded-t-lg bg-sky-500" style={{ height: Math.max(8, n / max * 120) }} /><Text className="mt-1 text-[10px] text-slate-500">{date.slice(5)}</Text></View>)}</View></View><View className="mt-3 rounded-2xl bg-white p-4"><Text className="text-base font-extrabold text-slate-900">Attendance trend</Text><Svg width="100%" height="150" viewBox="0 0 600 150" className="mt-3">{daily.length > 1 ? <Path d={daily.map(([, n], i) => `${i ? "L" : "M"} ${i / (daily.length - 1) * 560 + 20} ${135 - n / max * 110}`).join(" ")} fill="none" stroke="#0284c7" strokeWidth="5" /> : null}{daily.map(([, n], i) => <Circle key={i} cx={daily.length === 1 ? 300 : i / (daily.length - 1) * 560 + 20} cy={135 - n / max * 110} r="6" fill="#0284c7" />)}</Svg></View></View></ScrollView>;
}
function Stat({ label, value, color }: { label: string; value: number; color: string }) { return <View className="min-w-[47%] flex-1 rounded-2xl bg-white p-4"><Text className="text-xs font-bold uppercase text-slate-500">{label}</Text><Text className={`mt-1 text-2xl font-extrabold ${color}`}>{value}</Text></View>; }
