import { useEffect, useState } from "react";
import type { FormEvent } from "react";
import useCurrentUser from "../hooks/useCurrentUser";
import { listMessages, sendMessage, updateMessage, type AppMessage, type MessageRecipient } from "../services/messages";
import { listTenants, type Tenant } from "../services/tenants";
import { listStaff, type Staff } from "../services/staff";

export default function Messages() {
  const { userDoc } = useCurrentUser();
  const isSuperAdmin = userDoc?.role === "super_admin" || (userDoc?.role as string | undefined) === "superadmin";
  const currentUid = userDoc?.uid ?? userDoc?.id;
  const [messages, setMessages] = useState<AppMessage[]>([]); const [tenants, setTenants] = useState<Tenant[]>([]); const [staff, setStaff] = useState<Staff[]>([]);
  const [recipient, setRecipient] = useState<MessageRecipient>(isSuperAdmin ? "all_tenants" : "super_admin"); const [tenantId, setTenantId] = useState(""); const [staffUid, setStaffUid] = useState(""); const [subject, setSubject] = useState(""); const [body, setBody] = useState(""); const [status, setStatus] = useState(""); const [editingId, setEditingId] = useState<string | null>(null);
  async function load() { setMessages(await listMessages()); if (isSuperAdmin) setTenants(await listTenants()); else setStaff(await listStaff()); }
  useEffect(() => { void load().catch((e) => setStatus(e.message)); }, [isSuperAdmin]);
  async function submit(e: FormEvent) { e.preventDefault(); try { if (editingId) { await updateMessage(editingId, subject, body); setMessages((rows) => rows.map((m) => m.id === editingId ? { ...m, subject: subject.trim(), body: body.trim() } : m)); setStatus("Message updated successfully."); } else { const sent = await sendMessage({ subject, body, recipient, recipientTenantId: recipient === "tenant_admin" ? tenantId : null, recipientStaffUid: recipient === "staff_member" ? staffUid : null, senderName: userDoc?.displayName ?? undefined }); setMessages((rows) => [sent, ...rows]); setStatus("Message sent successfully."); } setSubject(""); setBody(""); setEditingId(null); } catch (err: any) { setStatus(err.message ?? "Unable to save message."); } }
  return <main className="form-page"><div className="admin-header"><h1 className="admin-title">Admin communication</h1></div><div className="grid gap-4 lg:grid-cols-2"><form onSubmit={submit} className="form-panel space-y-3"><h2 className="text-lg font-extrabold">{editingId ? "Edit message" : "Compose message"}</h2>{!editingId ? <select value={recipient} onChange={(e) => setRecipient(e.target.value as MessageRecipient)} className="enterprise-input"><option value="super_admin">Super Admin</option>{isSuperAdmin ? <><option value="all_tenants">All tenant administrators</option><option value="tenant_admin">Individual tenant administrator</option></> : <><option value="tenant_staff">My organisation staff</option><option value="staff_member">Individual staff member</option></>}</select> : <p className="text-sm text-slate-500">Recipient and delivery scope cannot be changed.</p>}{isSuperAdmin && !editingId && recipient === "tenant_admin" ? <select value={tenantId} onChange={(e) => setTenantId(e.target.value)} className="enterprise-input"><option value="">Select tenant</option>{tenants.map((t) => <option key={t.id} value={t.id}>{t.name}</option>)}</select> : null}{!isSuperAdmin && !editingId && recipient === "staff_member" ? <select required value={staffUid} onChange={(e) => setStaffUid(e.target.value)} className="enterprise-input"><option value="">Select staff member</option>{staff.map((member) => <option key={member.id} value={member.userUid ?? member.id}>{member.name ?? member.email ?? "Staff member"}</option>)}</select> : null}<input required value={subject} onChange={(e) => setSubject(e.target.value)} className="enterprise-input" placeholder="Subject" /><textarea required value={body} onChange={(e) => setBody(e.target.value)} className="enterprise-input min-h-32" placeholder="Write your message..." /><button className="enterprise-button-primary" type="submit">{editingId ? "Save changes" : "Send message"}</button>{editingId ? <button type="button" onClick={() => { setEditingId(null); setSubject(""); setBody(""); }} className="ml-2 enterprise-button-secondary">Cancel</button> : null}{status ? <p className="text-sm font-medium text-slate-700">{status}</p> : null}</form><section className="form-panel"><h2 className="text-lg font-extrabold">Inbox</h2>{messages.length ? messages.map((m) => <article key={m.id} className="mt-3 rounded-lg border bg-slate-50 p-3"><h3 className="font-bold">{m.subject}</h3><p className="mt-1 text-sm">{m.body}</p>{m.senderUid === currentUid ? <button type="button" onClick={() => { setEditingId(m.id); setSubject(m.subject); setBody(m.body); setStatus(""); }} className="mt-2 text-xs font-bold text-blue-700">Edit</button> : null}</article>) : <p className="mt-3 text-sm">No messages yet.</p>}</section></div></main>;
}
