import { useEffect, useState } from "react";
import type { FormEvent } from "react";
import useCurrentUser from "../hooks/useCurrentUser";
import { listMessages, sendMessage, type AppMessage, type MessageRecipient } from "../services/messages";
import { listTenants, type Tenant } from "../services/tenants";

export default function Messages() {
  const { userDoc } = useCurrentUser(); const isSuperAdmin = userDoc?.role === "super_admin";
  const [messages, setMessages] = useState<AppMessage[]>([]); const [tenants, setTenants] = useState<Tenant[]>([]); const [recipient, setRecipient] = useState<MessageRecipient>(isSuperAdmin ? "all_tenants" : "super_admin"); const [tenantId, setTenantId] = useState(""); const [subject, setSubject] = useState(""); const [body, setBody] = useState(""); const [status, setStatus] = useState("");
  async function load() { setMessages(await listMessages()); if (isSuperAdmin) setTenants(await listTenants()); }
  useEffect(() => { void load().catch((e) => setStatus(e.message)); }, [isSuperAdmin]);
  async function submit(e: FormEvent) { e.preventDefault(); setStatus(""); try { await sendMessage({ subject, body, recipient, recipientTenantId: recipient === "tenant_admin" ? tenantId : null, senderName: userDoc?.displayName ?? undefined }); setSubject(""); setBody(""); setStatus("Message sent."); await load(); } catch (err: any) { setStatus(err.message ?? "Unable to send message."); } }
  return <main className="form-page"><div className="admin-header"><div><h1 className="admin-title">Admin communication</h1><p className="admin-subtitle">Send and receive operational messages securely.</p></div></div><div className="grid gap-4 lg:grid-cols-[minmax(0,1fr)_minmax(0,1fr)]"><form onSubmit={submit} className="form-panel space-y-3"><h2 className="text-lg font-extrabold text-slate-900">Compose message</h2><select value={recipient} onChange={(e) => setRecipient(e.target.value as MessageRecipient)} className="enterprise-input"><option value="super_admin">Super Admin</option>{isSuperAdmin ? <option value="all_tenants">All tenant administrators</option> : null}<option value="tenant_admin">Individual tenant administrator</option></select>{recipient === "tenant_admin" ? <select value={tenantId} onChange={(e) => setTenantId(e.target.value)} className="enterprise-input"><option value="">Select tenant</option>{tenants.map((t) => <option key={t.id} value={t.id}>{t.name}</option>)}</select> : null}<input required value={subject} onChange={(e) => setSubject(e.target.value)} className="enterprise-input" placeholder="Subject" /><textarea required value={body} onChange={(e) => setBody(e.target.value)} className="enterprise-input min-h-32" placeholder="Write your message..." /><button className="enterprise-button-primary" type="submit">Send message</button>{status ? <p className="text-sm font-medium text-slate-700">{status}</p> : null}</form><section className="form-panel"><h2 className="text-lg font-extrabold text-slate-900">Inbox</h2>{messages.length ? messages.map((m) => <article key={m.id} className="mt-3 rounded-lg border border-slate-200 bg-slate-50 p-3"><h3 className="font-bold text-slate-900">{m.subject}</h3><p className="mt-1 text-sm text-slate-700">{m.body}</p></article>) : <p className="mt-3 text-sm text-slate-700">No messages yet.</p>}</section></div></main>;
}
