import { addDoc, arrayUnion, collection, doc, getDocs, query, serverTimestamp, updateDoc, where } from "firebase/firestore";
import { auth, db } from "../firebase";
import { getTenantScope, withTenantScope } from "./tenantScope";

export type MessageRecipient = "all_tenants" | "super_admin" | "tenant_admin" | "tenant_staff" | "staff_member";
export type AppMessage = { id: string; subject: string; body: string; senderUid: string; senderName?: string; recipient: MessageRecipient; recipientTenantId?: string | null; createdAt?: any; readBy?: string[] };
export async function sendMessage(input: { subject: string; body: string; recipient: MessageRecipient; recipientTenantId?: string | null; recipientStaffUid?: string | null; senderName?: string }): Promise<AppMessage> { const scope = await getTenantScope(); const uid = auth.currentUser?.uid; if (!uid) throw new Error("Sign in required."); if (scope.role !== "admin" && !scope.isSuperAdmin) throw new Error("Administrator permission is required."); if (input.recipient === "all_tenants" || input.recipient === "tenant_admin") { if (!scope.isSuperAdmin) throw new Error("Only Super Admin can contact tenant administrators."); if (input.recipient === "tenant_admin" && !input.recipientTenantId) throw new Error("Select a tenant."); } if ((input.recipient === "tenant_staff" || input.recipient === "staff_member") && (!scope.tenantId || input.recipientTenantId !== scope.tenantId)) throw new Error("Staff messages must stay within your organisation."); if (input.recipient === "staff_member" && !input.recipientStaffUid) throw new Error("Select a staff member."); const payload = withTenantScope({ ...input, recipientTenantId: input.recipient === "tenant_staff" || input.recipient === "staff_member" ? scope.tenantId : input.recipientTenantId ?? null, recipientStaffUid: input.recipientStaffUid ?? null, senderUid: uid, createdAt: serverTimestamp(), readBy: [] }, scope); const ref = await addDoc(collection(db, "messages"), payload); return { id: ref.id, ...(payload as any) } as AppMessage; }
export async function listMessages() { const scope = await getTenantScope(); const uid = auth.currentUser?.uid; if (!uid) return []; const base = collection(db, "messages"); const refs = scope.isSuperAdmin ? [query(base, where("recipient", "==", "tenant_admin")), query(base, where("recipient", "==", "all_tenants")), query(base, where("senderUid", "==", uid))] : [query(base, where("recipient", "==", "super_admin")), query(base, where("recipient", "==", "all_tenants")), query(base, where("recipient", "==", "tenant_staff"), where("recipientTenantId", "==", scope.tenantId)), query(base, where("recipient", "==", "staff_member"), where("recipientTenantId", "==", scope.tenantId), where("recipientStaffUid", "==", uid)), query(base, where("senderUid", "==", uid))]; const snaps = await Promise.all(refs.map(getDocs)); const map = new Map<string, AppMessage>(); snaps.forEach((snap) => snap.docs.forEach((d) => map.set(d.id, { id: d.id, ...(d.data() as any) } as AppMessage))); return [...map.values()].sort((a, b) => String(b.createdAt ?? "").localeCompare(String(a.createdAt ?? ""))); }
export async function updateMessage(id: string, subject: string, body: string) { if (!subject.trim() || !body.trim()) throw new Error("Subject and message body are required."); await updateDoc(doc(db, "messages", id), { subject: subject.trim(), body: body.trim() }); }
export async function markMessageRead(id: string) { const uid = auth.currentUser?.uid; if (!uid) return; await updateDoc(doc(db, "messages", id), { readBy: arrayUnion(uid) }); }
