import { addDoc, collection, doc, getDocs, query, serverTimestamp, updateDoc } from "firebase/firestore";
import { auth, db } from "../firebase";
import { getTenantScope, withTenantScope } from "./tenantScope";

export type MessageRecipient = "all_tenants" | "super_admin" | "tenant_admin" | "tenant_staff" | "staff_member";
export type AppMessage = { id: string; subject: string; body: string; senderUid: string; senderName?: string; recipient: MessageRecipient; recipientTenantId?: string | null; createdAt?: any; readBy?: string[] };
export async function sendMessage(input: { subject: string; body: string; recipient: MessageRecipient; recipientTenantId?: string | null; recipientStaffUid?: string | null; senderName?: string }): Promise<AppMessage> { const scope = await getTenantScope(); const uid = auth.currentUser?.uid; if (!uid) throw new Error("Sign in required."); if (scope.role !== "admin" && !scope.isSuperAdmin) throw new Error("Administrator permission is required."); if (input.recipient === "all_tenants" || input.recipient === "tenant_admin") { if (!scope.isSuperAdmin) throw new Error("Only Super Admin can contact tenant administrators."); if (input.recipient === "tenant_admin" && !input.recipientTenantId) throw new Error("Select a tenant."); } if ((input.recipient === "tenant_staff" || input.recipient === "staff_member") && (!scope.tenantId || input.recipientTenantId !== scope.tenantId)) throw new Error("Staff messages must stay within your organisation."); if (input.recipient === "staff_member" && !input.recipientStaffUid) throw new Error("Select a staff member."); const payload = withTenantScope({ ...input, recipientTenantId: input.recipient === "tenant_staff" || input.recipient === "staff_member" ? scope.tenantId : input.recipientTenantId ?? null, recipientStaffUid: input.recipientStaffUid ?? null, senderUid: uid, createdAt: serverTimestamp(), readBy: [] }, scope); const ref = await addDoc(collection(db, "messages"), payload); return { id: ref.id, ...(payload as any) } as AppMessage; }
export async function listMessages() { const scope = await getTenantScope(); if (!auth.currentUser?.uid) return []; const refs = scope.isSuperAdmin ? [query(collection(db, "messages"))] : [query(collection(db, "messages")),]; const snaps = await Promise.all(refs.map(getDocs)); const map = new Map<string, AppMessage>(); snaps.forEach((snap) => snap.docs.forEach((d) => { const data = d.data() as any; if (scope.isSuperAdmin || data.senderUid === auth.currentUser?.uid || data.recipient === "super_admin" || data.recipient === "all_tenants" || (data.tenantId === scope.tenantId && (data.recipient === "tenant_staff" || (data.recipient === "staff_member" && data.recipientStaffUid === auth.currentUser?.uid)))) map.set(d.id, { id: d.id, ...data } as AppMessage); })); return [...map.values()].sort((a, b) => String(b.createdAt ?? "").localeCompare(String(a.createdAt ?? ""))); }
export async function updateMessage(id: string, subject: string, body: string) { if (!subject.trim() || !body.trim()) throw new Error("Subject and message body are required."); await updateDoc(doc(db, "messages", id), { subject: subject.trim(), body: body.trim() }); }
